#!/usr/bin/env python3
"""
从环境变量 SITE_BASE 生成站点根目录下的 sitemap.xml。

用法:
  SITE_BASE=https://你的域名 python3 scripts/gen-sitemap.py
  SITE_BASE=https://user.github.io/仓库名 python3 scripts/gen-sitemap.py

SITE_BASE 不要末尾斜杠；若站点在子路径，请包含子路径（无尾斜杠）。
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from evolution_pkg.io import REPO_ROOT

REGISTRY_PATH = REPO_ROOT / "scripts" / "evolution-registry.json"

PRIORITY: dict[str, tuple[str, str]] = {
    "index.html": ("weekly", "1.0"),
    "nexus.html": ("monthly", "0.95"),
    "decade.html": ("monthly", "0.9"),
    "decade-scenes.html": ("monthly", "0.9"),
    "synthesis.html": ("monthly", "0.9"),
    "synthesis-extensions.html": ("monthly", "0.88"),
    "synthesis-methods.html": ("monthly", "0.88"),
    "modules-map.html": ("monthly", "0.85"),
    "decade-us.html": ("monthly", "0.85"),
    "edu-nexus.html": ("monthly", "0.85"),
    "evolution-triad.html": ("monthly", "0.85"),
    "work-infra-energy.html": ("monthly", "0.85"),
    "past-future.html": ("monthly", "0.8"),
    "net-biz-capital.html": ("monthly", "0.8"),
    "national-strategy-opinion.html": ("monthly", "0.82"),
    "social-responsibility-evolution.html": ("monthly", "0.815"),
    "evolution-loop.html": ("monthly", "0.83"),
    "analysis-hub.html": ("monthly", "0.82"),
    "intelligent-evolution.html": ("monthly", "0.81"),
    "evolvable-architecture.html": ("monthly", "0.805"),
    "risk-geo.html": ("monthly", "0.8"),
    "model.html": ("monthly", "0.8"),
    "architecture.html": ("monthly", "0.8"),
    "timeline.html": ("monthly", "0.75"),
    "lab.html": ("monthly", "0.75"),
    "legacy-all-in-one.html": ("yearly", "0.4"),
}

DEFAULT = ("monthly", "0.8")

# 不参与站点地图（错误页、归档单文件等）
SKIP_HTML = frozenset({"404.html"})


def main() -> None:
    base = os.environ.get("SITE_BASE", "").strip().rstrip("/")
    if not base:
        print(
            "错误: 请设置 SITE_BASE，例如:\n"
            "  SITE_BASE=https://example.org python3 scripts/gen-sitemap.py",
            file=sys.stderr,
        )
        sys.exit(1)
    if not base.startswith(("http://", "https://")):
        print("错误: SITE_BASE 须以 http:// 或 https:// 开头", file=sys.stderr)
        sys.exit(1)

    if not REGISTRY_PATH.is_file():
        print(f"错误: 缺少注册表 {REGISTRY_PATH}", file=sys.stderr)
        sys.exit(1)
    reg = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    reg_pages = {str(p).strip() for p in (reg.get("pages") or []) if str(p).strip()}
    for k in PRIORITY:
        if k not in reg_pages:
            print(
                f"错误: PRIORITY 键「{k}」不在 evolution-registry.json pages",
                file=sys.stderr,
            )
            sys.exit(1)

    pages = sorted(
        p.name for p in REPO_ROOT.glob("*.html") if p.name not in SKIP_HTML
    )
    if "index.html" in pages:
        pages.remove("index.html")
        pages.insert(0, "index.html")

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- generated by scripts/gen-sitemap.py · SITE_BASE={base} -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for name in pages:
        cf, pr = PRIORITY.get(name, DEFAULT)
        loc = f"{base}/{name}"
        lines.append(
            f"  <url><loc>{loc}</loc><changefreq>{cf}</changefreq><priority>{pr}</priority></url>"
        )
    lines.append("</urlset>")

    out = REPO_ROOT / "sitemap.xml"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"已写入 {out}（{len(pages)} 条 URL）")


if __name__ == "__main__":
    main()
